x-environment-defaults: &environment-defaults
  DEBUG: "False"
  POSTGRES_DB: "beam"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "anas"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: 5432

services:
  db:
    image: postgres:14
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anas
      - POSTGRES_DB=beam
#      - POSTGRES_HOST=localhost
    ports:
      - "5433:5432"
  web:
    build: .
    container_name: beam
    ports:
      - 8000:8000
    environment:
      <<: *environment-defaults
    depends_on:
      - db

volumes:
  postgres_data:
